discussion/urls.py
from django.conf.urls.defaults import *
from django.views.generic import RedirectView

from discussion.views import (DiscussionList, DiscussionView,
                              CreatePost, PostView, Search)


urlpatterns = patterns('discussion.views',
    url(r'^$', DiscussionList.as_view(), name='discussion_index'),
    url(r'^search/$', Search.as_view(), name='discussion_search'),
    url(r'^discussions/', include(patterns('',
        url(r'^$', RedirectView.as_view(url='../')),
        url(r'^(?P<slug>[\w-]+)/$', DiscussionView.as_view(), name='discussion'),
        url(r'^(?P<discussion_slug>[\w-]+)/posts/$', RedirectView.as_view(url='../')),
        url(r'^(?P<discussion_slug>[\w-]+)/posts/add/$', CreatePost.as_view(), name='discussion_add_post'),
        url(r'^(?P<discussion_slug>[\w-]+)/posts/(?P<pk>[\d]+)/$', PostView.as_view(), name='discussion_post'),
    )))
)

discussion/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import date, time
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver

from notification.models import NoticeType, create_notice_type, send
from orderable.models import Orderable


class Discussion(Orderable):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    image = models.ImageField(upload_to='images/discussions', max_length=255, blank=True, null=True)
    description = models.TextField(default='', blank=True, null=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('discussion', [self.slug])

    @property
    def notification_label(self):
        return "discussion_remind_%s" % self.slug

    @property
    def notification_display(self):
        return ("Notification for %s." % self.name)[:50]

    @property
    def notice_type(self):
        """
            Return the notice type for this discussion.
            If it does not exist then the notice type will be created.
        """
        self.create_notice_type()
        return NoticeType.objects.get(label=self.notification_label)

    def create_notice_type(self):
        """Create (or update) a notice type for discussion instance."""
        create_notice_type(
                label=self.notification_label,
                display=self.notification_display,
                description="A new post has been added .",
                slug=self._meta.app_label,
                default=0)


class Post(models.Model):
    discussion = models.ForeignKey(Discussion)
    user = models.ForeignKey(User)
    body = models.TextField()
    attachment = models.FileField(upload_to='uploads/posts', blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-time',)

    def __unicode__(self):
        return 'Post by {user} at {time} on {date}'.format(
            user=self.user,
            time=time(self.time),
            date=date(self.time),
        )

    @models.permalink
    def get_absolute_url(self):
        return ('discussion_post', [self.discussion.slug, str(self.id)])

    @property
    def attachment_filename(self):
        return self.attachment and os.path.basename(self.attachment.name)

    @property
    def prefix(self):
        return 'post-%d' % (self.pk or 0,)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)
    body = models.TextField()
    attachment = models.FileField(upload_to='uploads/comments',
                                    blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)

    @property
    def attachment_filename(self):
        return self.attachment and os.path.basename(self.attachment.name)

    class Meta:
        ordering = ('time',)

    def __unicode__(self):
        return 'Comment by {user} at {time} on {date}'.format(
            user=self.user,
            time=time(self.time),
            date=date(self.time),
        )


@receiver(post_save, sender=Discussion)
def create_discussion_notice_type(sender, instance, **kwargs):
    # If display or diary title has changed notification details will be updated or created for new diary.
    instance.create_notice_type()


@receiver(pre_delete, sender=Discussion)
def delete_discussion_notice_type(sender, instance, **kwargs):
    instance.notice_type.delete()


def notify_discussion_subscribers(discussion, instance):
    """
        Notifies all users who have their notification settings set to True for given discussion
        instance parameter here is either Post or Comment
    """
    notification_label = discussion.notification_label
    users = User.objects.filter(
            noticesetting__send=True,
            noticesetting__notice_type__label=notification_label).exclude(id=instance.user.id).distinct()
    send(users, notification_label, {'discussion': discussion}, now=True)


def post_notifications(sender, instance, created, **kwargs):
    if created:
        notify_discussion_subscribers(instance.discussion, instance)
models.signals.post_save.connect(post_notifications, sender=Post)


def comment_notifications(sender, instance, created, **kwargs):
    if created:
        notify_discussion_subscribers(instance.post.discussion, instance)
models.signals.post_save.connect(comment_notifications, sender=Comment)

discussion/templates/discussion/_comment_detail.html
<div class="comment" id="comment-{{ comment.id }}">
    <h5 class="user-name">{{ comment.user.get_full_name }}</h5>
    <p class="comment-body">{{ comment.body|urlize|linebreaksbr }}</p>
    <time datetime="{{ comment.time }}" class="comment-date">{{ comment.time|timesince }} ago</time>
    {% if comment.attachment %}
        <div class="comment-attachment">
            <a class="attachment-file" href="{{ comment.attachment.url }}">{{ comment.attachment_filename }}</a>
        </div>
    {% endif %}
</div>

discussion/templates/discussion/_post_detail.html
{% load discussiontags %}
<header class="post-header">
  <div class="post-author">
    <h5 class="user-name">{{ post.user.get_full_name }}</h5>
    <time pubdate="{{ post.time }}" class="post-date">{{ post.time|date:"d/m/Y" }}</time>
  </div>
</header>
<section class="post-body">
  {% if search_term %}
      {{ post.body|urlize|linebreaks|highlight:search_term }}
  {% else %}
      {{ post.body|urlize|linebreaks }}
  {% endif %}
</section>
{% if post.attachment %}
<div class="post-attachment">
    <a class="attachment-file" href="{{ post.attachment.url }}">{{ post.attachment_filename }}</a>
</div>
{% endif %}

discussion/templates/discussion/_post_form_fields.html
{% csrf_token %}
{{ form.non_field_errors }}
<div class="body-field">
  {{ form.body }}
  {{ form.body.errors }}
</div>
<div class="file-upload-field">
  <label for="id_{{ form.attachment.html_name }}">Add a file:</label>
  {{ form.attachment }}
  {{ form.attachment.errors }}
</div>
<span class="button"><input type="submit" value="Post"></span>

discussion/templates/discussion/_search_form.html
<form action="{% url discussion_search %}" method="POST" class="forum-search-form">
  {% csrf_token %}
  {{ search_form.as_p }}
  <span class="button"><input type="submit" value="search"></span>
</form>

discussion/templates/discussion/base.html
{% extends "base.html" %}

{% block bodyclass %}{{ block.super }} discussion{% endblock %}

{% block content %}
  <div id="forum-content">
    {% block forum_content %}{% endblock %}
  </div>
{% endblock content %}

{% comment %}Copy this to project and uncomment the extra_style and extra_script blocks below to include the default JS and CSS on discussion pages. You might need to adjust the two block names to fit your template.{% endcomment %}

{% comment %}
{% block extra_style %}<link rel="stylesheet" href="{{ STATIC_URL }}discussion/styles/discussion.css">{% endblock extra_style %}
{% block extra_script %}
<script type="text/javascript" src="{{ STATIC_URL }}scripts/plugins/jquery.form.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}scripts/plugins/jquery.autogrow.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}scripts/plugins/jquery.placeholder.js"></script>
<script src="{{ STATIC_URL }}discussion/scripts/discussion.js"></script>
{% endblock extra_script %}
{% endcomment %}

discussion/templates/discussion/comment_form.html
<form class="comment-form" action="{% url discussion_post pk=post.pk discussion_slug=post.discussion.slug %}" method="POST" enctype="multipart/form-data">
    <h3>Add new reply:</h5>
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="body-field">
      {{ form.body }}
      {{ form.body.errors }}
    </div>
    <div class="file-upload-field">
      <label for="id_{{ form.attachment.html_name }}">Add a file:</label>
      {{ form.attachment }}
      {{ form.attachment.errors }}
    </div>
    <span class="button"><input type="submit" value="Comment"></span>
</form>

discussion/templates/discussion/discussion_detail.html
{% extends "discussion/base.html" %}
{% load discussiontags %}

{% block forum_content %}
    <div class="forum-search">
        <h2>Search</h2>
        {% include 'discussion/_search_form.html' %}
    </div>
    
    <h2>{{ object }}</h2>
    <div class="posts_wrapper">
        <form action="{% url discussion_add_post discussion_slug=object.slug %}" method="POST" enctype="multipart/form-data" class="post-form">
            <h3>Add new post:</h3>
            {% include 'discussion/_post_form_fields.html' %}
        </form>
        {% for post in object.post_set.all %}
            <article class="post post-list-{{ forloop.counter }}" id="post-{{ post.id }}">
                {% url discussion_post pk=post.pk discussion_slug=object.slug as post_detail %}
                <div class="post-info">
                    {% include 'discussion/_post_detail.html' %}
                    <div class="comment-count">{{ post.comment_set.all.count|default:"No" }} repl{{ post.comment_set.all.count|pluralize:"y,ies" }}</div>
                    <div class="post-links">
                        <a href="#reply-{{ forloop.counter }}" class="post-reply">Reply</a>
                        <a href="{{ post_detail }}" class="post-permalink">Full conversation</a>
                    </div>
                </div>
                <section class="post-comments">
                    {% if post.comment_set.all.count > 0 %}
                        <h3 class="replies">Replies:</h3>
                        {% for comment in post.comment_set.all %}
                            {% include 'discussion/_comment_detail.html' %}
                        {% endfor %}
                    {% endif %}
                    <div class="comment-form-wrapper" id="reply-{{ forloop.counter }}">
                        {% comment_form post %}
                    </div>
                </section>
            </article>
        {% endfor %}
    </div>
    <a href="{% url discussion_index %}" class="index-link">All discussions</a>
{% endblock %}

discussion/templates/discussion/discussion_list.html
{% extends "discussion/base.html" %}

{% block forum_content %}
    <div class="forum-search">
        <h2>Search</h2>
        {% include 'discussion/_search_form.html' %}
    </div>

    <h2>Discussions</h2>
    <ul class="discussion-list">
        {% for obj in object_list %}
            <li><a href="{% url discussion slug=obj.slug %}">{{ obj }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

discussion/templates/discussion/limit_comments.html
{% for comment in first_comments %}
    {% include 'discussion/_comment_detail.html' %}
{% endfor %}
{% if hidden_count %}
    <div class="comment show-hidden">
        <a href="{% url discussion_post pk=post.pk discussion_slug=post.discussion.slug %}">Show {{ hidden_count }} hidden repl{{ hidden_count|pluralize:"y,ies"}}</a>
    </div>
{% endif %}
{% for comment in last_comments %}
    {% include 'discussion/_comment_detail.html' %}
{% endfor %}

discussion/templates/discussion/post_detail.html
{% extends "discussion/base.html" %}
{% load discussiontags %}

{% block bodyclass %}{{ block.super }} post-view{% endblock %}

{% block forum_content %}
    <article class="post" id="post-{{ post.id }}">
        <div class="post-info">
            {% include 'discussion/_post_detail.html' %}
            <div class="comment-count">{{ post.comment_set.all.count|default:"No" }} repl{{ post.comment_set.all.count|pluralize:"y,ies" }}</div>
            <div class="post-links">
                <a href="#reply" class="post-reply">Reply</a>
            </div>
        </div>
        <section class="post-comments">
            {% if post.comment_set.all.count > 0 %}
                <h3 class="replies">Replies:</h3>
                {% for comment in post.comment_set.all %}
                    {% include 'discussion/_comment_detail.html' %}
                {% endfor %}
            {% endif %}
            <div class="comment-form-wrapper" id="reply">
                {% comment_form post %}
            </div>
        </section>
    </article>

    <a href="{% url discussion slug=post.discussion.slug %}" class="index-link">All posts in {{ post.discussion }}</a>
{% endblock %}

discussion/templates/discussion/post_form.html
{% extends "discussion/base.html" %}

{% block forum_content %}
    <h2>Add a Post</h2>
    <form action="{% url discussion_add_post discussion_slug=discussion.slug %}" method="POST" enctype="multipart/form-data" class="post-form">
        {% include 'discussion/_post_form_fields.html' %}
    </form>

    <a href="{% url discussion slug=discussion.slug %}" class="index-link">All posts in {{ discussion }}</a>
{% endblock %}

discussion/templates/discussion/search.html
{% extends "discussion/base.html" %}

{% block forum_content %}
    <div class="forum-search">
        <h2>Search</h2>
        {% include 'discussion/_search_form.html' %}
    </div>

    <div class="forum-search-results">
    {% if object_list %}
        <h5><span class="num-results">{{ object_list.all.count }}</span> results</h5>
        {% for post in object_list %}
            <article class="post" id="post-{{ post.id }}">
                <div class="post-info">
                    {% include 'discussion/_post_detail.html' %}
                    <div class="comment-count">{{ post.comment_set.all.count|default:"No" }} repl{{ post.comment_set.all.count|pluralize:"y,ies" }}</div>
                    <div class="post-links">
                        <a href="{% url discussion_post discussion_slug=post.discussion.slug pk=post.pk %}" class="post-permalink">Full conversation</a>
                    </div>
                </div>
            </article>
        {% endfor %}
    {% else %}
        <p>No results</p>
    {% endif %}
    </div>

    <a href="{% url discussion_index %}" class="index-link">All discussions</a>
{% endblock %}